name: Setup Remote Access

on:
  workflow_dispatch:
    inputs:
      auth_code:
        description: 'Chrome Remote Desktop Authorization Code'
        required: true

jobs:
  setup-remote-access:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set CRD_AUTH_CODE
      run: echo "CRD_AUTH_CODE=${{ github.event.inputs.auth_code }}" >> $env:GITHUB_ENV

    - name: Construct CRD Command
      run: |
        $crdHostPath = "${Env:PROGRAMFILES(X86)}\Google\Chrome Remote Desktop\CurrentVersion\remoting_start_host.exe"
        $authCode = "${{ github.event.inputs.auth_code }}"
        $redirectUrl = "https://remotedesktop.google.com/_/oauthredirect"
        $computerName = $Env:COMPUTERNAME

        $crdCommand = @(
            $crdHostPath,
            "--code=$authCode",
            "--redirect-url=$redirectUrl",
            "--name=$computerName"
        )
        
        echo "CRD_COMMAND=@($($crdCommand -join ' '))" >> $env:GITHUB_ENV
      shell: pwsh


    - name: Setup Chrome Remote Desktop
      shell: pwsh
      run: |
        & ./setup-crd.ps1
