name: Setup Windows RDP with Ngrok

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  setup-rdp:
    runs-on: windows-latest
    timeout-minutes: 420  # Thiết lập thời gian chạy tối đa là 7 giờ (420 phút)

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up ngrok
      run: |
        # Lưu ngrok token từ GitHub Secrets vào môi trường
        echo "NGROK_TOKEN=${{ secrets.NGROK_AUTH_TOKEN }}" >> $env:GITHUB_ENV

    - name: Run PowerShell script to setup RDP and Ngrok
      shell: pwsh
      run: |
        powershell -ExecutionPolicy Bypass -File "./setup-rdp.ps1"
