name: RDP Setup with Chrome Remote Desktop

on:
  push:
    branches:
      - main

jobs:
  setup-rdp-chrome-remote-desktop:
    runs-on: windows-latest

    steps:
      - name: Set up RDP on Windows
        run: |
          # Mở cổng RDP (3389) trong tường lửa
          New-NetFirewallRule -DisplayName "Open RDP Port" -Enabled True -Protocol TCP -Action Allow -Direction Inbound -LocalPort 3389
          
          # Cài đặt RDP nếu chưa cài
          $rdp = Get-WindowsFeature -Name Remote-Desktop-Services
          if (-not $rdp.Installed) {
            Install-WindowsFeature -Name Remote-Desktop-Services
          }
          
          # Khởi động dịch vụ Remote Desktop
          Start-Service -Name TermService
          
          # Tạo tài khoản người dùng cho RDP
          $userName = "rdpuser"
          $password = "P@ssw0rd123!"  # Đảm bảo mật khẩu phức tạp đủ
          $securePassword = ConvertTo-SecureString $password -AsPlainText -Force
          New-LocalUser -Name $userName -Password $securePassword -FullName "RDP User" -Description "User for RDP Access"
          Add-LocalGroupMember -Group "Administrators" -Member $userName

      - name: Download and Install Chrome Remote Desktop Host
        run: |
          # Tải xuống và cài đặt Chrome Remote Desktop Host
          Invoke-WebRequest -Uri "https://dl.google.com/edgedl/chrome-remote-desktop/chromeremotedesktophost.msi" -OutFile "chromeremotedesktophost.msi"
          Start-Process -FilePath "chromeremotedesktophost.msi" -ArgumentList "/quiet" -Wait

      - name: Start Chrome Remote Desktop
        env:
          COMPUTERNAME: ${{ runner.os }}
          REMOTE_CODE: "4/0ASVgi3Kg4L2i4Cn9CYDCgj_NYCWFD3Wj0a1By5RIfSKq7AzyjR5oNbJy73xeKLne24sjyw"  # Thay bằng mã OAuth của bạn
        run: |
          # Khởi động Chrome Remote Desktop Host
          Start-Process -FilePath "${Env:PROGRAMFILES(X86)}\Google\Chrome Remote Desktop\CurrentVersion\remoting_start_host.exe" -ArgumentList "--code=$env:REMOTE_CODE --redirect-url=https://remotedesktop.google.com/_/oauthredirect --name=$Env:COMPUTERNAME"
          
          # Đợi thông báo yêu cầu mã PIN và tự động nhập "123456"
          Write-Host "Vui lòng nhập mã PIN tự động."
          Start-Sleep -Seconds 10  # Đợi một chút để cửa sổ yêu cầu mã PIN xuất hiện (tùy chỉnh nếu cần)
          
          # Tự động gửi mã PIN "123456"
          Add-Type -AssemblyName "System.Windows.Forms"
          [System.Windows.Forms.SendKeys]::Send("123456{ENTER}")
          Write-Host "Mã PIN đã nhập tự động: 123456"

      - name: Wait for 6 hours
        run: |
          # Sau khi nhập mã PIN, giữ kết nối RDP trong 6 giờ
          Write-Host "Đang giữ kết nối RDP trong 6 giờ..."
          Start-Sleep -Seconds 21600  # 6 giờ = 21600 giây

      - name: Clean up
        run: |
          # Dừng Chrome Remote Desktop và RDP nếu cần
          Stop-Process -Name "remoting_start_host" -Force
          Stop-Service -Name TermService
