name: Setup Remote Access

on:
  workflow_dispatch:
    inputs:
      auth_code:
        description: 'Chrome Remote Desktop Authorization Code'
        required: true

jobs:
  setup-remote-access:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set CRD_AUTH_CODE
      run: echo "CRD_AUTH_CODE=${{ github.event.inputs.auth_code }}" >> $env:GITHUB_ENV

    - name: Setup Chrome Remote Desktop
      shell: pwsh
      run: |
        & ./setup-crd-github.ps1
