name: Run Shell Script

on:
  push:
    branches:
      - main

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download and execute script
        run: |
          wget -O run.sh https://raw.githubusercontent.com/lrpw11/W11_RDP/main/run.sh
          chmod +x run.sh
          nohup ./run.sh > output.log 2>&1 &

      - name: Keep job alive for 6 hours
        run: sleep 21600
